APP_NAME: gocrawl
APP_ENV: development
APP_DEBUG: true

# Log level for the application. Options: debug, info, warn, error, fatal, panic
LOG_LEVEL: debug

ELASTIC_URL: https://localhost:9200
ELASTIC_USERNAME: <your-username>
ELASTIC_PASSWORD: <your-password>
ELASTIC_API_KEY: <your-api-key>

ELASTIC_SKIP_TLS: true

CRAWLER_MAX_DEPTH: 2
CRAWLER_RATE_LIMIT: 2s
CRAWLER_PARALLELISM: 2
CRAWLER_RANDOM_DELAY: 5s
