app:
  environment: production
  name: gocrawl
  version: 0.1.0
  debug: false

elasticsearch:
  addresses:
    - "https://es.streetcode.net"
  username: ""  # Using API key authentication instead
  password: ""  # Using API key authentication instead
  api_key: ""   # Set via ELASTIC_API_KEY environment variable
  auth_type: "apikey"  # Explicitly set to use API key
  tls:
    enabled: true
    skip_verify: false  # Matches ELASTIC_SKIP_TLS in supervisor
  retry:
    enabled: true
    initial_wait: 1s
    max_wait: 30s
    max_retries: 3

crawler:
  max_depth: 2
  rate_limit: "2s"
  parallelism: 2
  random_delay: "5s"
  source_file: "sources.yml"

log:
  level: info  # Can be overridden by LOG_LEVEL env var
  debug: false 

server:
  address: "8085"  # Can be overridden by GOCRAWL_PORT env var
  read_timeout: 10s
  write_timeout: 30s
  idle_timeout: 60s
  