sources:
  - name: "Elliot Lake Today"
    url: "https://www.elliotlaketoday.com/opp-beat"
    index: "elliot_lake_articles"
  
  - name: "Espanola News"
    url: "https://www.myespanolanow.com/news/"
    index: "espanola_articles"

  - name: "Mid North Monitor"
    url: "https://www.midnorthmonitor.com/category/news/local-news/"
    index: "mid_north_articles"
