version: '3'

tasks:
  crawl:
    desc: "Run the web crawler"
    cmds:
      - go run main.go crawl -u https://www.elliotlaketoday.com/opp-beat -d 2 -r 2s -i articles

  crawl:multi:
    desc: "Run the web crawler for multiple sources defined in sources.yml"
    cmds:
      - go run main.go multi --source "Mid North Monitor"

  search:
    desc: "Search crawled content"
    cmds:
      - go run main.go search -q "{{.CLI_ARGS}}" -i elliotlake_elliotlaketoday_articles

  build:
    desc: "Build the web crawler executable"
    cmds:
      - mkdir -p bin
      - go build -o bin/gocrawl main.go

  lint:
    desc: "Lint the Go code"
    cmds:
      - go fmt ./...
      - go vet ./...
      - golangci-lint run ./...

  test:
    desc: "Run the tests"
    cmds:
      - go test -v ./...

  test:cover:
    desc: "Run tests with coverage"
    cmds:
      - mkdir -p coverage
      - go test -coverprofile=coverage/coverage.out ./...
      - go tool cover -html=coverage/coverage.out -o coverage/coverage.html
      - go tool cover -func=coverage/coverage.out
    generates:
      - coverage/coverage.out
      - coverage/coverage.html

  help:
    desc: "Show available commands"
    cmds:
      - go run main.go --help
