version: '3'

tasks:
  crawl:
    desc: "Run the web crawler"
    cmds:
      - go run main.go crawl -u https://www.elliotlaketoday.com/opp-beat -d 2 -r 2s

  search:
    desc: "Search crawled content"
    cmds:
      - go run main.go search -q "{{.CLI_ARGS}}" -i pages

  build:
    desc: "Build the web crawler executable"
    cmds:
      - mkdir -p bin
      - go build -o bin/gocrawl main.go

  lint:
    desc: "Lint the Go code"
    cmds:
      - go vet ./...
      - golangci-lint run ./...

  test:
    desc: "Run the tests"
    cmds:
      - go test -v ./...

  help:
    desc: "Show available commands"
    cmds:
      - go run main.go --help
