version: '3'

tasks:
  api:
    desc: "Run the HTTP API server"
    cmds:
      - go run main.go httpd
    ignore_error: true
    interactive: true

  build:
    desc: "Build the web crawler executable"
    cmds:
      - mkdir -p bin
      - go build -o bin/gocrawl main.go

  crawl:
    desc: "Run the web crawler for a single source defined in sources.yml"
    cmds:
      - echo '' > app.log
      - go run main.go indices delete --source {{.CLI_ARGS | trim}} --force || true
      - go run main.go crawl {{.CLI_ARGS | trim}}
      - go run main.go indices list
    interactive: true

  deadcode:
    desc: "Find unreachable functions in the codebase"
    cmds:
      - deadcode -test -generated ./...
    ignore_error: true

  help:
    desc: "Show available commands"
    cmds:
      - go run main.go --help

  indices:create:
    desc: "Create an Elasticsearch index"
    cmds:
      - go run main.go indices create {{.CLI_ARGS}}
    ignore_error: true
    interactive: true

  indices:list:
    desc: "List all Elasticsearch indices"
    cmds:
      - go run main.go indices list
    ignore_error: true

  indices:delete:
    desc: "Delete one or more Elasticsearch indices"
    cmds:
      - |
        if [ "{{.SOURCE}}" != "" ]; then
          go run main.go indices delete --source "{{.SOURCE}}" {{if .FORCE}}--force{{end}}
        else
          go run main.go indices delete {{.CLI_ARGS}}
        fi
    ignore_error: true
    interactive: true
    vars:
      SOURCE: '{{.SOURCE | default ""}}'
      FORCE: '{{.FORCE | default "false"}}'

  job:
    desc: "Run the job scheduler for automated crawling based on sources.yml schedules"
    cmds:
      - go run main.go job
    ignore_error: true
    interactive: true

  lint:
    desc: "Lint the Go code"
    cmds:
      - go fmt ./...
      - go vet ./...
      - golangci-lint run ./...

  search:
    desc: "Search crawled content"
    cmds:
      - go run main.go search -q "{{.CLI_ARGS}}" -i elliotlake_elliotlaketoday_articles
    ignore_error: true
    interactive: true

  sources:list:
    desc: "List all sources"
    cmds:
      - go run main.go sources list
    ignore_error: true

  test:
    desc: "Run the tests"
    cmds:
      - go test -v ./...

  test:cover:
    desc: "Run tests with coverage"
    cmds:
      - mkdir -p coverage
      - go test -coverprofile=coverage/coverage.out ./...
      - go tool cover -html=coverage/coverage.out -o coverage/coverage.html
      - go tool cover -func=coverage/coverage.out
    generates:
      - coverage/coverage.out
      - coverage/coverage.html
