@baseUrl = http://localhost:8080
@contentType = application/json

### Health Check
GET {{baseUrl}}/health
Content-Type: {{contentType}}

### Search
POST {{baseUrl}}/search
Content-Type: {{contentType}}

{
    "query": "test",
    "index": "articles",
    "size": 10
}

### Search with empty query
POST {{baseUrl}}/search
Content-Type: {{contentType}}

{
    "query": "",
    "index": "articles",
    "size": 10
}

### Search with invalid index
POST {{baseUrl}}/search
Content-Type: {{contentType}}

{
    "query": "test",
    "index": "invalid_index",
    "size": 10
}

### Search with invalid size
POST {{baseUrl}}/search
Content-Type: {{contentType}}

{
    "query": "test",
    "index": "articles",
    "size": -1
} 